name: Robot Framework Tests API

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

env:
  BASE_URL: ${{ secrets.BASE_URL }}
  API_USERNAME: ${{ secrets.API_USERNAME }}
  API_PASSWORD: ${{ secrets.API_PASSWORD }}

jobs:
  robot-tests:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute Robot Tests
        run: |
          robot --outputdir results tests

      - name: Upload Robot Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: robot-results
          path: results/